declare module "react-simple-chatbot";
declare module "react-render-html";
declare module "query-string";
declare module "mic-recorder-to-mp3";
declare module "react-ratings-declarative";
declare module '*.woff';
declare module '*.woff2';
declare module '*.tiff';
declare module "react-expand-animated";
declare module "swiper";
declare module "*.jpg";
declare module "*.png";
declare module "*.svg";
declare module 'react-file-viewer'
declare module 'react-file-viewer-extended'
//declare module "wavesurfer-react";